### ISSUE TITLE
About copy and move semantic of class Individual

### ISSUE THREAD

**Issue by ChicoChen** [ChicoChen/PPf24-SnakeGame#9]
@Cutiemango 我注意到在 Class Individual 的 class member 裡面有一個 undefined 的 copy constructor
`Individual(const Individual& other);`  

https://github.com/ChicoChen/PPf24-SnakeGame/blob/f9255efd17170f562f1f0416a76467409353f38f/include/ga/individual.h#L6-L19  

但追朔回去到 include/nn/neural_network.h 的話會發現由於 Layer 類別內的 class member: weights 是 std::unique_ptr<float[]>, Layer 刪除了自己的 copy constructor. 
因為我現在的code 在 line 17 跟 line 58 會用到 Individual 的 copy constructor,
所以我想先確認一下 Individual 的 copy constructor 實做後的行為 

https://github.com/ChicoChen/PPf24-SnakeGame/blob/d47db85efab5de841268ed0006500c6926bd182b/lib/ga/base_ga.cpp#L17
https://github.com/ChicoChen/PPf24-SnakeGame/blob/d47db85efab5de841268ed0006500c6926bd182b/lib/ga/base_ga.cpp#L58

**Comment by Cutiemango** [comment]
> 我現在的 code 在 line 17 跟 line 58 會用到 Individual 的 copy constructor

你這裡的 copy 會是甚麼 scenario 下使用?

**Comment by Cutiemango** [comment]
看了一下，就我的認知 shuffle 應該不會需要 copy
然後 getBestIndividual 應該可以回傳 reference?

**Comment by ChicoChen** [comment]
了解，getBestIndividual() 那邊我剛修改好了
